services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:14.8-alpine3.18
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    restart: on-failure

  backend:
    container_name: app
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"


  frontend:
    container_name: bot
    build: ./frontend
    depends_on:
      - redis
      - backend
    volumes:
      - ./frontend:/bot

