"""empty message

Revision ID: 1b9683002169
Revises: 8c44419036bf
Create Date: 2024-12-01 13:26:33.730121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b9683002169"
down_revision: Union[str, None] = "8c44419036bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("telegram_id_idx", "users", ["telegram_id"], unique=False)
    op.create_index("username_idx", "users", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("username_idx", table_name="users")
    op.drop_index("telegram_id_idx", table_name="users")
    # ### end Alembic commands ###
