"""empty message

Revision ID: 8c44419036bf
Revises: 19c9c83b6d28
Create Date: 2024-11-25 21:09:05.746684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c44419036bf"
down_revision: Union[str, None] = "19c9c83b6d28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_uniq_date_habit", "tracking", ["date", "habit_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_uniq_date_habit", "tracking", type_="unique")
    # ### end Alembic commands ###
