"""empty message

Revision ID: 19c9c83b6d28
Revises: 328423042570
Create Date: 2024-11-25 17:18:14.366616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19c9c83b6d28"
down_revision: Union[str, None] = "328423042570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habits", sa.Column("completed_at", sa.Date(), nullable=True)
    )
    op.drop_column("habits", "is_done")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habits",
        sa.Column(
            "is_done", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("habits", "completed_at")
    # ### end Alembic commands ###
