"""empty message

Revision ID: 42fce86b90bf
Revises: 2293f8e3694a
Create Date: 2024-11-25 13:49:13.124447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42fce86b90bf"
down_revision: Union[str, None] = "2293f8e3694a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habits", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "habits", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "tracking", sa.Column("habit_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "tracking", "habits", ["habit_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tracking", type_="foreignkey")
    op.drop_column("tracking", "habit_id")
    op.drop_constraint(None, "habits", type_="foreignkey")
    op.drop_column("habits", "user_id")
    # ### end Alembic commands ###
